name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean compile -DskipTests
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: HotbarManager API ${{ github.ref_name }}
        body: |
          ## HotbarManager API ${{ github.ref_name }}
          
          ### What's New
          - Complete API interface for HotbarManager plugin
          - Event system for addon development
          - Example addons included (HotbarStatsAddon, HotbarSyncAddon)
          - Comprehensive documentation and guides
          
          ### Installation
          Download the source code and build with Maven:
          ```bash
          git clone https://github.com/Pro-Nil/HotbarManager-API.git
          cd HotbarManager-API
          mvn clean package
          ```
          
          ### Documentation
          - [API Documentation](https://github.com/Pro-Nil/HotbarManager-API/blob/main/README.md)
          - [Example Addons](https://github.com/Pro-Nil/HotbarManager-API/tree/main/examples)
          
          ### Example Addons
          - **HotbarStatsAddon**: Tracks player statistics and usage patterns
          - **HotbarSyncAddon**: Team-based hotbar synchronization system
        files: |
          src/
          examples/
          README.md
          LICENSE
          pom.xml
        draft: false
        prerelease: false